# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*
- release/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'
    workingDir: 'src'

- task: Npm@1
  displayName: npm audit
  inputs:
    command: 'custom'
    workingDir: 'src'
    customCommand: 'audit'